version: "3"
services:
  server:
    build:
      context: .
      dockerfile: docker/server/development/Dockerfile
    container_name: server
    environment:
      - NODE_ENV=development
    volumes:
      - ./packages/server/:/app/packages/server/
      - ./packages/shared/:/app/packages/shared/
      - server_modules:/app/packages/server/node_modules
      - ./yarn.lock:/app/yarn.lock:cached
      - ./package.json:/app/package.json:cached
    ports:
      - "9001:9001"
    depends_on:
      - redis
      - shared
  shared:
    build:
      context: .
      dockerfile: docker/shared/development/Dockerfile
    container_name: shared
    environment:
      - NODE_ENV=development
    volumes:
      - ./packages/shared:/app/packages/shared
      - ./yarn.lock:/app/yarn.lock:cached
      - ./package.json:/app/package.json:cached
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data

volumes:
  redis-volume:
  node_modules:
  client_modules:
  server_modules:

